# Generated by Django 4.1 on 2022-12-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmnzApp', '0007_service_form_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_freelance',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='register_freelance',
            name='w_status',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
