# Generated by Django 4.0.4 on 2022-12-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmnzApp', '0007_service_form_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_form',
            name='file',
            field=models.FileField(null=True, upload_to='image'),
        ),
    ]
