# Generated by Django 4.0.4 on 2022-12-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmnzApp', '0008_service_form_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_form',
            name='file',
            field=models.FileField(default='null', null=True, upload_to='image'),
        ),
    ]
