# Generated by Django 4.1 on 2022-12-14 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmnzApp', '0009_freelancerworks'),
    ]

    operations = [
        
    ]
