# Generated by Django 4.0.4 on 2022-12-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmnzApp', '0009_alter_service_form_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_form',
            name='service_freelancer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
