# Generated by Django 4.1 on 2022-12-14 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmnzApp', '0010_remove_service_form_service_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_form',
            name='service_freelancer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dmnzApp.register_freelance'),
        ),
    ]
