# Generated by Django 4.0.4 on 2022-12-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmnzApp', '0011_rename_file_register_freelance_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_freelance',
            name='work_1',
            field=models.FileField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
