# Generated by Django 4.1 on 2022-12-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmnzApp', '0011_service_form_service_freelancer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Freelancerworks',
        ),
    ]
