# Generated by Django 4.0.4 on 2022-12-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmnzApp', '0012_register_freelance_work_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_freelance',
            old_name='url',
            new_name='Total_exp',
        ),
    ]
