# Generated by Django 4.1 on 2022-12-14 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dmnzApp', '0013_freelancerworks_delete_service_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('Address', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dmnzApp.product')),
                ('service_freelancer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dmnzApp.register_freelance')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
