# Generated by Django 4.0.4 on 2022-12-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmnzApp', '0013_rename_url_register_freelance_total_exp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_freelance',
            old_name='project_title',
            new_name='Address',
        ),
        migrations.AddField(
            model_name='register_freelance',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    
    ]
