# Generated by Django 4.1 on 2022-12-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmnzApp', '0016_register_freelance_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerworks',
            name='submitte_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
