# Generated by Django 4.1 on 2022-12-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmnzApp', '0018_freelancerworks_fr_service_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_form',
            name='user',
        ),
        migrations.AddField(
            model_name='service_form',
            name='categori',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='service_form',
            name='product',
            field=models.IntegerField(default='0'),
        ),
    ]
