# Generated by Django 4.1 on 2022-12-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmnzApp', '0019_remove_service_form_user_service_form_categori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerworks',
            name='fr_categori',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='freelancerworks',
            name='fr_product',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='freelancerworks',
            name='fr_user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
