# Generated by Django 4.1 on 2023-01-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmnzApp', '0021_messagebox'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_freelance',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
