# Generated by Django 4.1 on 2023-01-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmnzApp', '0022_register_freelance_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagebox',
            name='mg_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
