# Generated by Django 4.1 on 2023-01-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmnzApp', '0024_service_form_req_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerworks',
            name='fr_desecr',
            field=models.TextField(default=''),
        ),
    ]
