# Generated by Django 4.1 on 2023-02-02 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmnzApp', '0028_product_fr_id_product_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_freelance',
            name='service',
        ),
        migrations.RemoveField(
            model_name='register_freelance',
            name='work_1',
        ),
        migrations.RemoveField(
            model_name='register_freelance',
            name='work_2',
        ),
        migrations.RemoveField(
            model_name='register_freelance',
            name='work_3',
        ),
        migrations.CreateModel(
            name='FreelancerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default='', max_length=255)),
                ('work_1', models.FileField(blank=True, default='', null=True, upload_to='images/')),
                ('work_2', models.FileField(blank=True, default='', null=True, upload_to='images/')),
                ('work_3', models.FileField(blank=True, default='', null=True, upload_to='images/')),
                ('free_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmnzApp.register_freelance')),
            ],
        ),
    ]
